name: flutter_flavorizr_extended
description: extended flutter_flavorizr for updateRun
version: 0.0.6
repository: https://github.com/Guo-astro/flutter_flavorizor_extended
issue_tracker: https://github.com/Guo-astro/flutter_flavorizor_extended/issues
homepage: https://github.com/Guo-astro/flutter_flavorizor_extended

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.10.0 <=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.1
  args: ^2.6.0
  checked_yaml: ^2.0.3
  collection: ^1.18.0
  image: ^4.3.0
  io: ^1.0.4
  json_annotation: ^4.9.0
  sprintf: ^7.0.0
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
